- set_fact:
    tds: "{{ ansible_date_time.epoch }}"

- rds:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    command: create
    backup_retention: "{{ backup_retention }}"
    instance_name: "{{ rds_instance_name }}"
    region: "{{ region }}"
    wait: yes
    wait_timeout: 1200
    db_engine: "{{ db_engine }}"
    size: "{{ db_size }}"
    instance_type: "{{ instance_type }}"
    username: "{{ db_username }}"
    password: "{{ db_password }}"
    db_name: "{{ db_name }}"
    port: "{{ port }}"
    vpc_security_groups: "{{ vpc_security_groups }}"
    publicly_accessible: yes
    subnet: "{{ subnet }}"
    tags:
      Application: ansible-rds
      Description: "{{ ansible_user_id }} RDS {{ db_engine }} {{ tds }}"
  register: rds
  when: state=="present"

- rds:
    command: delete
    region: "{{ region }}"
    instance_name: "{{ rds_instance_name }}"
  when: state=="absent"

- name: retrieve rds endpoint IP
  shell: "getent hosts {{ rds.instance.endpoint }} | awk '{ print $1 }'"
  register: rds_endpoint_ip
  when: state=="present"


- name: Create Kube Secrets
  when: state=="present"
  k8s_raw:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ rds_instance_name }}"
        namespace: "{{ namespace }}"
      type: Opaque
      data:
        DB_HOST: "{{ rds_endpoint_ip.stdout | b64encode }}"
        DB_PORT: "{{ port | b64encode }}"
        DB_USER: "{{ db_username | b64encode }}"
        DB_PASSWORD: "{{ db_password | b64encode }}"
        DB_NAME: "{{ db_name | b64encode }}"

- name: Delete Kube Secrets
  when: state=="absent"
  k8s_raw:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ rds_instance_name }}"
        namespace: "{{ namespace }}"
